spring:
  datasource:
    url: jdbc:h2:mem:ju-market-app_db
    username: Filipe
    password:
  jpa:
    show-sql: true
    #hibernate:

    propreties:
      hibernate.format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
