CREATE TABLE carrinho (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   id_product BIGINT NOT NULL,
   product_name VARCHAR(20) NOT NULL,
   product_quatity INT NOT NULL,
   product_price DECIMAL NOT NULL,
   CONSTRAINT pk_carrinho PRIMARY KEY (id)
);