CREATE TABLE pedidos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   product_name VARCHAR(30) NOT NULL,
   id_product BIGINT NOT NULL,
   unit_price DECIMAL(10, 2) NOT NULL,
   quatity INT NOT NULL,
   payment_form VARCHAR(255) NOT NULL,
   vending_code VARCHAR(255) NOT NULL,
   CONSTRAINT pk_pedidos PRIMARY KEY (id)
);